#This is the name of the github workflow
name: Chatbot CI

#Definds when the workflow should run. In this case every push and pull request on the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

#Definds the jobs that will run in the workflow
jobs:
  #Everything that will be run in the job
  build-and-publish:
    #This is cool, it will make a temp ubuntu machine to run this test
    runs-on: ubuntu-latest
    #Starts the steps from the top to the bottom
    steps:
      #downloads the code from the repo to the temp machine
      - name: Checkout repository
        uses: actions/checkout@v4
      #sets up a node.js environment on the temp machine, and caches the npm dependencies for faster builds
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      #Installs the dependencies. Ci is designed for a CI environment that will install the exact versions 
      - name: Install dependencies
        run: npm ci
      #run the project test.
      - name: Run tests
        run: npm test 

      #Logs into the github registry to push the docker image. 
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #Builds the docker image and tags it with the latest tag.
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/bobthefish29/emergingtechnologiesproposal:latest \
            -t ghcr.io/bobthefish29/emergingtechnologiesproposal:${{ github.sha }} \
            .
      #Pushes the docker image to the github registry.
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/bobthefish29/emergingtechnologiesproposal:latest
          docker push ghcr.io/bobthefish29/emergingtechnologiesproposal:${{ github.sha }}